### PR TITLE
Crash Fix:  Global set_animation is nil when trying to ride a dragon.

### PR DESCRIPTION
**Pull request by ghost**
Change set_animation to mobs:set_animation fixes this.

### CODE REVIEW

**Comment by D00Med** [comment]
Thanks, I will merge this, but you should know that this isn't the only bug. 
I stopped updating the mod a while ago.

**Comment by ghost** [comment]
Is there a follow-on or new maintainer?

**Comment by taikedz** [comment]
I wonder if it's worth doing a group that specifically maintains `mobs_redo`-based mods, into which mobs mods can be released to for collaborative continued maintenance...? I'm maintaining a couple that were left stagnant...

**Comment by D00Med** [comment]
@argyle77 Not at the moment, I had started a newer version but I dropped it.
@taikedz That sounds like a good idea. I think there is a group that maintains mods in general, iirc it was organised by Rubenwardy. You are welcome to take over the project if you like, since you understand it the most.

**Comment by ghost** [comment]
@DOOMed Its a good addition.  Thanks for writing it.  If it doesn't bother you, I'll continue to report fixes as I find them.
@taikedz That sounds like a good idea.  I'm kinda new to this process, so I wouldn't know where to start, but I'll prolly try to go look at that Rubenwardy stuff.

**Comment by D00Med** [comment]
You're welcome. That is fine with me.

**Comment by taikedz** [comment]
@D00Med I believe that would be the [minetest-mods](/minetest-mods) group, according to their homepage, original mod author needs to submit the request. If that involves procedure you're not of interest in pursuing, I'd be happy to fork `dmobs` into a [minetest-mobs-mods](/minetest-mobs-mods) group on the basis of your comments here.

**Pull request merged**
